package com.gl.ceir.config.model.constants;

public enum RulesNames {
	LBD, EXISTS_IN_TAC_DB, EXISTS_IN_TYPE_APPROVED_DB, IMEI_LUHN_CHECK, EXISTS_IN_USAGE_DB, 
	EXIST_IN_IMPORTER_DB, EXIST_IN_DISTRIBUTOR_DB, EXIST_IN_RETAILER_DB, EXIST_IN_CUSTOM_DB,
	EXIST_IN_MANUFACTURER_DB, EXIST_IN_END_USER_DB, IMEI_LENGTH, EXISTS_IN_REGULARIZED_DB, 
	IMEI_NULL;
}
