package com.gl.ceir.config.model.constants;

public interface Tags {

	String CUSTOMS_TAX_STATUS = "CUSTOMS_TAX_STATUS";
	String CUSTOMS_PORT = "CUSTOMS_PORT";
	String SOURCE_TYPE = "SOURCE_TYPE";
	String REQ_TYPE = "REQ_TYPE";
	String OPERATORS = "OPERATORS";
	String DEVICE_ID_TYPE = "DEVICE_ID_TYPE";
	String DEVICE_TYPE = "DEVICE_TYPE";
	String CURRENCY = "CURRENCY";
	String DEVICE_STATUS = "DEVICE_STATUS";
	String FILE_TYPE = "FILE_TYPE";
	String BLOCK_CATEGORY = "BLOCK_CATEGORY";
	String CONFIG_TYPE = "CONFIG_TYPE";
	String DOC_TYPE = "DOC_TYPE";
	String CHANNEL = "CHANNEL";
	String IS_ACTIVE = "IS_ACTIVE";
	String ALERT_STATE = "ALERT_STATE";
	String DELETE_FLAG = "DELETE_FLAG";
	String MULTI_SIM_STATUS = "MULTI_SIM_STATUS";
	String VISA_TYPE = "VISA_TYPE";
	String COMPLAINT_TYPE = "COMPLAINT_TYPE";
}
